---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: v1.7.1
  manager:
    featureGates:
      ClusterTopology: true
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: talos
spec:
  version: v0.6.4
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: talos
  spec:
  version: v0.5.6
---
apiVersion: v1
kind: Secret
metadata:
  name: talos-variables
type: Opaque
data:
  # https://www.sidero.dev/v0.6/overview/installation/
  # https://www.sidero.dev/v0.6/getting-started/install-clusterapi/
  SIDERO_CONTROLLER_MANAGER_HOST_NETWORK: "dHJ1ZQo="  # true
  SIDERO_CONTROLLER_MANAGER_DEPLOYMENT_STRATEGY: "UmVjcmVhdGUK"  # Recreate
  SIDERO_CONTROLLER_MANAGER_API_ENDPOINT: "MTAuMjAuMC4xMAo="  # 10.20.0.10
  SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT: "MTAuMjAuMC4xMAo="  # 10.20.0.10
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: sidero
spec:
  version: v0.6.4
  configSecret:
    name: talos-variables
