---
controller:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: 'kaas/group'
  #               operator: In
  #               values:
  #                 - 'control'
speaker:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: 'kaas/group'
  #               operator: In
  #               values:
  #                 - 'compute'
