  # Create worker node machine templates for all supported k8s versions and availability zones
{{- range $version := $.Values.supported.k8s_versions }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: {{$.Values.tenant}}-workers-{{ regexReplaceAll "\\W+" $version "-" }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: none
      virtualMachineTemplate:
        metadata:
          namespace: tenant-{{$.Values.tenant}}
          labels:
            cluster.x-k8s.io/cluster-name: "{{$.Values.tenant}}"
            cluster.x-k8s.io/role: worker
        spec:
          runStrategy: Once  # https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/main/docs/faq.md#whenever-i-reboot-a-vm-in-kubevirt-it-loseschanges-its-ip-address-how-do-i-fix-it
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      {% comment %} - matchExpressions:
                          - key: 'kaas/group'
                            operator: In
                            values:
                              - 'compute' {% endcomment %}
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: "topology.kubernetes.io/zone"
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      cluster.x-k8s.io/cluster-name: {{$.Values.tenant}}
                - maxSkew: 1
                  topologyKey: "kubernetes.io/hostname"
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      cluster.x-k8s.io/cluster-name: {{$.Values.tenant}}
              # networks:
              #   - name: default
              #     pod: {}
              domain:
                cpu:
                  cores: {{int $.Values.cluster.workers.cores}}
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
                  # interfaces:
                  #   # - name: default
                  #   #   bridge: {}
                  #   - name: default
                  #     masquerade: {}
                  #     ports:
                  #       - name: ssh
                  #         port: 22
                memory:
                  guest: {{$.Values.cluster.workers.memory}}
              evictionStrategy: External
              volumes:
                - containerDisk:
                    image: localhost:30303/kubevirt/{{$.Values.cluster.image}}-{{ $version }}-container-disk:latest
                    imagePullPolicy: Always
                    # image: quay.io/capk/ubuntu-2004-container-disk:{{ $version }}
                  name: containervolume
{{- end }}
