---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server
  labels:
    app: image-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.17
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: webroot
              mountPath: /webroot
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: webroot
          hostPath:
            path: /opt/image-server
            type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /webroot;

        location / {
            allow   11.11.11.11/27;
            allow   10.0.0.0/8;
            deny    all;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: image-server
spec:
  selector:
    app: image-server
  ports:
    - protocol: TCP
      port: 30101
      nodePort: 30101
      targetPort: 80
  type: NodePort
