apiVersion: crd.projectcalico.org/v1
kind: IPAMConfig
metadata:
  name: default
spec:
  autoAllocateBlocks: true
  # https://docs.tigera.io/calico/3.24/getting-started/kubernetes/windows-calico/quickstart#configure-strict-affinity-for-clusters-using-calico-networking
  strictAffinity: true
