---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capi-kubevirt
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            clusterType: host
  template:
    metadata:
      name: '{{name}}--capi-kubevirt'
    spec:
      project: default
      source:
        repoURL: https://github.com/kubernetesproject123/mgmnt-cluster-argocd-base
        targetRevision: main
        path: add-ons/capi-kubevirt
      destination:
        server: '{{server}}'
        namespace: capi-kubevirt
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
