---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-api-operator
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.10.1
    helm:
      releaseName: capi-operator
      values: |
        resources:
          manager:
            limits:
              cpu: null
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /spec/conversion/webhook/clientConfig
  destination:
    server: https://kubernetes.default.svc
    namespace: capi-operator-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
