---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hcloud-cloud-controller-manager
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  provider: "hetzner"
          - clusters:
              selector:
                matchLabels:
                  clusterType: "mgmnt"
  template:
    metadata:
      name: '{{name}}--hcloud-cloud-controller-manager'
    spec:
      project: default
      source:
        chart: hcloud-cloud-controller-manager
        repoURL: https://charts.hetzner.cloud
        targetRevision: v1.19.0
        helm:
          releaseName: hcloud-cloud-controller-manager
          values: |
            env:
              HCLOUD_LOAD_BALANCERS_LOCATION:
                valueFrom:
                  secretKeyRef:
                    name: hcloud-ccm
                    key: location
              HCLOUD_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: hcloud-{{values.postfix}}
                    key: hcloud
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
