---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  provider: "novoserve"
          - clusters:
              selector:
                matchLabels:
                  clusterType: "mgmnt"
  template:
    metadata:
      name: '{{name}}--ingress-nginx'
    spec:
      project: default
      source:
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.10.0
        helm:
          releaseName: ingress-nginx
          valuesObject:
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: 30080
                  https: 30443
      destination:
        server: '{{server}}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
