---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetesproject123/mgmnt-cluster-argocd-base
    targetRevision: main
    path: add-ons/kyverno-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno-policies
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
