#
# https://github.com/samba-in-kubernetes/samba-operator/blob/master/docs/README.md
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: samba-operator
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            clusterType: "host"
  template:
    metadata:
      name: '{{name}}--samba-operator'
    spec:
      project: default
      source:
        repoURL: https://github.com/kubernetesproject123/mgmnt-cluster-argocd-base
        targetRevision: main
        path: add-ons/samba-operator
      destination:
        server: '{{server}}'
        namespace: smb-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
