---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: smb-csi
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            clusterType: "tenant"
  template:
    metadata:
      name: '{{name}}--smb-csi'
    spec:
      project: default
      source:
        chart: csi-driver-smb
        repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
        targetRevision: v1.14.0
        helm:
          releaseName: csi-driver-smb
          values: |
            windows:
              enabled: true
              csiproxy:
                enabled: true
      destination:
        server: '{{server}}'
        namespace: smb-csi
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
