---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-clusters-hcloud
spec:
  generators:
    - git:
        repoURL: https://github.com/kubernetesproject123/mgmnt-cluster-argocd-tenants
        revision: HEAD
        files:
          - path: "tenants/hcloud/**/config.yaml"
  template:
    metadata:
      name: 'tenant-{{tenant}}-cluster-hcloud'
    spec:
      project: default
      ignoreDifferences:
        - group: "*"
          kind: "MachineDeployment"
          jsonPointers:
            - /spec/selector/matchLabels
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          # - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: https://github.com/kubernetesproject123/mgmnt-cluster-argocd-base
        targetRevision: HEAD
        path: clusters/hcloud
        helm:
          values: |
            tenant: '{{tenant}}'
            cluster:
              k8s_version: '{{cluster.k8s_version}}'
              image: '{{cluster.image}}'
              controlplane:
                count: '{{cluster.controlplane.count}}'
                instance_type: '{{cluster.controlplane.instance_type}}'
              workers:
                count: '{{cluster.workers.count}}'
                instance_type: '{{cluster.workers.instance_type}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'tenant-{{tenant}}'
