---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-nginx-proxy
  labels:
    app: loki-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-nginx-proxy
  template:
    metadata:
      labels:
        app: loki-nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: auth-secret
              mountPath: /etc/nginx/auth
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: auth-secret
          secret:
            secretName: loki-basic-auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            auth_basic "Restricted Area";
            auth_basic_user_file /etc/nginx/auth/.htpasswd;

            proxy_pass http://loki-stack:3100;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
# https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
apiVersion: v1
data:
  .htpasswd: bG9raTokYXByMSRRTWVmWHpSRiRySXNLNUEzeWM4TDc4T24zU095eVkxCg==
kind: Secret
metadata:
  name: loki-basic-auth
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: loki-nginx-proxy
  annotations:
    metallb.universe.tf/loadBalancerIPs: 11.11.11.11
spec:
  selector:
    app: loki-nginx-proxy
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 80
  type: LoadBalancer
  # loadBalancerIP: 11.11.11.11
