---
apiVersion: v1
kind: Secret
metadata:
  name: tinkerbell-oci
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ghcr.io/tinkerbell/charts
  type: helm
  name: tinkerbell
  enableOCI: "true"
